### ISSUE TITLE
[RFH] smc.eachMapping is not a function

### ISSUE THREAD

**Issue by mirabilos** [mozilla/source-map#524]
I got reported a [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1134275) about a package of mine no longer building. It uses source-map during build, in [this script](https://sources.debian.org/data/main/d/dygraphs/2.2.1-4/scripts/env-patcher.js), and the method is still documented in <https://github.com/mozilla/source-map/blob/master/README.md#sourcemapconsumerprototypeeachmappingcallback-context-order>, so I have no idea what is going wrong here.

Help would be appreciated.

**Comment by bomsy** [comment]
Hi, I guess this is your package https://github.com/danvk/dygraphs. I'm not sure what the issue might be. But your package seems to using the 0.6.1 of source-map which seem quite old. Have you tried bumping to a newer version (0.7.x) to see if it fixes it?

**Comment by mirabilos** [comment]
On Fri, 24 Apr 2026, Hubert Boma Manilla wrote:

>Hi, I guess this is your package https://github.com/danvk/dygraphs. I'm

Yes.

>not sure what the issue might be. But your package seems to using the
>0.6.1 of source-map which seem quite old. Have you tried bumping to a
>newer version (0.7.x) to see if it fixes it?

The problem is that it works with 0.6 but not with 0.7 and Debian
has just upgraded to 0.7 so the build in Debian now breaks.

**Comment by mirabilos** [comment]
So, what incompatible change did you do to break this with 0.7?

**Comment by mirabilos** [comment]
What changed between 0.6 and 0.7 to break existing code? So I can adapt.

**Comment by bomsy** [comment]
0.7 starts using wasm for the sourceMapConsumer https://github.com/mozilla/source-map/commit/86d105bfda30fc71aba95c21f2e665a384b5b69f

**Comment by mirabilos** [comment]
I’ve now found that, in *theory*, the following diff fixes my problem:

```
-const smc = new SourceMapConsumer(JSON.parse(inMap));
+const smc_ = new SourceMapConsumer(JSON.parse(inMap));
+// work around breaking change in source-map
+const smc = ('sourceRoot' in smc_) ? smc_ : await smc_;
```

In *practice* however, this caused me untold amounts of trouble, because nodejs refuses to run top-level `await` statements. 🤬

Could you not have kept the API and added the asynchronous crap under **different** names?
