### ISSUE TITLE
currentCallback is not a function

### ISSUE THREAD

**Issue by coocooooo** [mozilla/source-map#338]
os: win10
node: v8.5.0
source-map: 0.7.2

the below function will run into error **currentCallback is not a function**
```javascript
function mergeSourcemap(
  sourceMapConsumer_1,
  sourceMapConsumer_2
) {
    sourceMapConsumer_2.eachMapping((mappingItem) => {
    const { source, column, line } = sourceMapConsumer_1.originalPositionFor({
      column: m.originalColumn,
      line: m.originalLine,
    });
  });
}
```
I guess it is caused by I invoke `originnalPositionFor` method of `consumer_1` in the `eachMapping` method of `consumer_2`. 
and for your reference, the same code work well in the **source-map@0.5.6**

**Comment by mjomble** [comment]
I just ran into the same problem about 20 minutes after you created the issue :)

Temporary workaround that uses more memory:

```javascript
const mappingItems = [];

sourceMapConsumer_2.eachMapping((mappingItem) => mappingItems.push(mappingItem));

// The consumer can be destroyed before the for loop 
sourceMapConsumer_2.destroy();

for (const mappingItem of mappingItems) {
  const { source, column, line } = sourceMapConsumer_1.originalPositionFor({
    column: mappingItem.originalColumn,
    line: mappingItem.originalLine,
  });
  ...
}

sourceMapConsumer_1.destroy();
```

**Comment by coocooooo** [comment]
@mjomble yes I do the same thing to work around, as mentioned in reference 1. It works. Wish mainteners have more gentleful solution.

**Comment by fitzgen** [comment]
Thanks for filing an issue.

I think this is a dupe of #330 and #319 -- can you reproduce on master?

**Comment by coocooooo** [comment]
@fitzgen great job, the master branch fix the issue, Looking forward to the release of the next version

**Comment by fitzgen** [comment]
Published 0.7.3
